# Generated by Django 2.0 on 2019-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_no', models.IntegerField(null=None)),
                ('company_name', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=20)),
                ('company_city', models.CharField(max_length=30)),
                ('company_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
